# -*- coding: utf-8 -*-
"""nba_EDA.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1c9X1Lszjuhbh_a6pP64JoP8lyyjtbIbf
"""

import numpy as np
import pandas as pd

nba = pd.read_csv("https://raw.githubusercontent.com/Malezaja/data/master/nba.csv", index_col='Unnamed: 0')
nba.head()

nba.shape

nba.columns

nba.dtypes

nba.tail()

nba.sample()

nba.info()

nba.describe()

nba.Age.describe()

nba['Age'].quantile(q = 0.25)

nba.describe(include='object')

nba.columns

nba.Team.unique()

nba.Team.value_counts()

nba.loc[(nba['Team'] == 'Los Angeles Lakers') & (nba['Position'] == 'C')]

nba.loc[(nba['Team'] == 'Boston Celtics') | (nba['Team'] == 'Philadelphia 76ers')]

nba.loc[(nba['Team'] == 'Miami Heat') & (nba['Age'] > 25)]

import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

nba.dropna(inplace=True)

nba.head()

team_salary = nba.groupby('Team', as_index = False)['Salary'].sum().sort_values(by = 'Salary', ascending = False)[:10]
team_salary

sns.catplot(x = 'Team', y = 'Salary', kind = 'bar', data = team_salary)
plt.xticks(rotation = 90);

pd.cut(nba.Age, 3, labels= ['young', 'medium', 'old'])

nba['Age_Group'] = pd.cut(nba.Age, 3, labels= ['young', 'medium', 'old'])

sns.catplot(data = nba, x = 'Age_Group', kind = 'count', hue = 'Position');

sns.boxplot(data = nba, x = 'Position', y = 'Salary');

sns.catplot(data = nba, x = 'Age_Group', y = 'Salary', kind= 'box');

fig, axs = plt.subplots(1,2, sharey=True, figsize = (10,5))

sns.boxplot(data = nba, x = 'Position', y = 'Salary', ax = axs[0])
sns.boxplot(data = nba, x = 'Age_Group', y = 'Salary', ax = axs[1]);

filtered_data = nba.loc[nba.Team.isin(team_salary.Team)]
filtered_data

table = filtered_data.pivot_table('Salary', index = 'Team', columns= 'Position')
table

sns.heatmap(data = table, cmap = 'coolwarm');